name: Output information

on:
    push:
        branches:
            - main
    pull_request:
        branches:
         - main
    workflow_dispatch:

jobs:
    info:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 20
            - name: Install dependencies
              run: npm install -g yarn && yarn install
            - name: Output information
              run: |
                echo "Node.js version:"
                node -v
                echo "Yarn version:"
                yarn -v
                echo "Installed packages:"
                yarn list --depth=0
            - name: Notify output completion
              run: echo "Output information completed successfully!"